### ISSUE TITLE
CHG: index.md instead of README.md

### ISSUE THREAD

**Issue by twilson63** [chscodecamp/CODEcampAS#2]
It may just be too confusing to use README.md as the index page, it may be better to use `index.md` as the convention and use the `README.md` to explain how to run the project.

**Comment by twilson63** [comment]
@rwcrosby  I changed the repo to drive the site from index.md files as root files versus `README`, `README` will be now used for contributor instructions

**Comment by rwcrosby** [comment]
@twilson63 Pulled the latest into my fork. Verified that I have the latest index.md and package.json. When I to 'npm start' and browse localhost:3000 I get the README.md file.

**Comment by twilson63** [comment]
Ok, more than likely the cache is not resetting. I will very I have the file cache set to 0

You can reset your cache if you want to forward

Cache should expire in an hour by default

Thx

Tom

**Comment by twilson63** [comment]
One think you can check is to make sure you have the latest version of codecamp kit installed

Just run

npm install

Then 

npm start

Thx

Tom

**Comment by rwcrosby** [comment]
Install then start worked. I'm getting the correct files now.

**Comment by twilson63** [comment]
:thumbs up:
