### ISSUE TITLE
LInks in the layouts demo

### ISSUE THREAD

**Issue by rwcrosby** [chscodecamp/CODEcampAS#27]
In the jsbin code called from /1-hello-world/4.md you have some `<a href='#'>` links in the example as well as a button in the exercise but we don't have any material introducing the concept of links or controls at that point. Should we either:

1). Go ahead and put in page to introduce links and another for controls.
or
2). Simplify the example removing the links and controls.

**Comment by twilson63** [comment]
I don't think we have to remove links in the demo, focusing on the semantic elements should prove to be fine, at least it has been my experience with the kids I have taught, and in the exercise, they are not asked to create links, only create a section and article element, I added some lorem ipsum to make it even easier.
