### ISSUE TITLE
First Web Page/name.md page

### ISSUE THREAD

**Issue by rwcrosby** [chscodecamp/CODEcampAS#29]
A couple of things relating to the the hyperdev example:

1). I can't find a download link on the page. How would one of the teachers download it if they want to?
2). If seems like a pretty complex example. You could spend a lot of time just explaining things like scripts at css at this early point in the learning process.

**Comment by twilson63** [comment]
_1.  I can't find a download link on the page. How would one of the teachers download it if they want to?_

Just sharing the url with the teacher, they can access and remix into their own account, it is actually pretty easy to use once provided a brief overview. (hopefully these screenshots help you find the download button)

<img width="700" alt="screen shot 2016-07-10 at 10 16 33 pm" src="https://cloud.githubusercontent.com/assets/21292/16718272/83a26464-46ec-11e6-8da7-b571d768837f.png">

<img width="908" alt="screen shot 2016-07-10 at 10 16 46 pm" src="https://cloud.githubusercontent.com/assets/21292/16718271/83a18c42-46ec-11e6-9b42-3ce1ecddda7f.png">

<img width="930" alt="screen shot 2016-07-10 at 10 16 58 pm" src="https://cloud.githubusercontent.com/assets/21292/16718270/83a00322-46ec-11e6-82ea-074780d68da4.png">
