### ISSUE TITLE
Magic 8 Ball Comments

### ISSUE THREAD

**Issue by rwcrosby** [chscodecamp/CODEcampAS#38]
@twilson63 

Some comments on the maze game:

1. On the functions page you reference an exercise 4 but there's no 4.md file. I've commented it out.
2. On the nested-functions page you reference an exercise 4 but the 4.md file ios empty. I've commented it out.
3. The App demo link takes you to a page the is pretty much a duplicate of the exercises. Is this intentional or perhaps should the demo just have a running 8 ball leaving the building of the page to the exercises.
4. The <script> mode of tonicdev doesn't seem to work, I've changed the uses to the <div> method which seems for stable.
5. The dom exercises are missing

**Comment by twilson63** [comment]
Modified demo to just show final result
