### ISSUE TITLE
Images not showning

### ISSUE THREAD

**Issue by rwcrosby** [chscodecamp/CODEcampAS#61]
During the class, when I (and several of the teachers) navigated to the online journal page from the link in slack, the logo image in the header and the logo in the footer did resolve:
<img width="1311" alt="screen shot 2016-08-06 at 13 01 16" src="https://cloud.githubusercontent.com/assets/341326/17458065/ecf06864-5bd5-11e6-99a3-d8060b18475b.png">

**Comment by twilson63** [comment]
Should be fixed
